// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SacMtgPlanner.Models;
using System;

namespace SacMtgPlanner.Migrations
{
    [DbContext(typeof(SacMtgPlannerContext))]
    partial class SacMtgPlannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacMtgPlanner.Models.Meeting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Benediction");

                    b.Property<string>("ClosingHymnName");

                    b.Property<decimal>("ClosingHymnNumber");

                    b.Property<string>("Conductor");

                    b.Property<string>("Invocation");

                    b.Property<DateTime>("MeetingDate");

                    b.Property<string>("OpeningHymnName");

                    b.Property<decimal>("OpeningHymnNumber");

                    b.Property<string>("SacHymnName");

                    b.Property<decimal>("SacHymnNumber");

                    b.Property<string>("SpeakerOne");

                    b.Property<string>("SpeakerTwo");

                    b.Property<string>("Subject");

                    b.Property<string>("YouthSpeaker");

                    b.HasKey("ID");

                    b.ToTable("Meeting");
                });
#pragma warning restore 612, 618
        }
    }
}
